const constants = {
  LOAD_SEARCH_RESULTS: 'LOAD_SEARCH_RESULTS',
  LOAD_SEARCH_RESULTS_SUCCESS: 'LOAD_SEARCH_RESULTS_SUCCESS',
  LOAD_SEARCH_RESULTS_ERROR: 'LOAD_SEARCH_RESULTS_ERROR',
  SORT_SEARCH_RESULTS: 'SORT_SEARCH_RESULTS'
}

export default constants
